[toc]

# 返回值和错误处理

Rust中的错误分为两类：

1.   可恢复错误：从系统全局角度来看可以接收的错误
2.   不可恢复的错误：全局性的或者系统性的错误

## Panic

~~~ rust
fn main() {
    panic!("error");
}
~~~

当出现`panic!`时，程序提供了两种方式来处理终止程序：

*   栈展开：Rust会回溯栈上数据和函数的调用，因此意味着更多的善后工作，好处是可以给出充分的报错信息和栈调用信息，便于事后的问题复盘。
*   直接终止：不清理数据就直接退出程序，善后工作交给操作系统来负责。

>   [!tip]
>
>   main进程在panic后，程序会终止，其他进程panic后，线程会终止，但是不影响main进程。

#### 示例、原型、测试

错误处理会拖慢编码的速度，当确切的知道，代码时正确的时候，可以使用`unwrap`、`expect`等方法来处理。

~~~ rust
use std::net::IpAddr;
let home:IpAddr = "127.0.0.1".parse().unwrap();
~~~

因为“127.0.0.1”就时一个ip地址，parse方法一定是正确的，所以可以直接使用unwrap来进行处理。

## 可恢复的错误 Result

~~~ rust
use std::fs::File;
fn main() {
    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("错误的打开文件{:?}",error)
        },
    };
}
~~~

### 对返回的错误进行处理

~~~ rust
use std::fs::File;
use std::io::ErrorKind;
fn main() {
    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("错误的创建文件{:?}",e),
            },
            other_error => panic!("错误的打开文件{:?}",other_error),
        },
    };
}
~~~

[简化错误处理](https://course.rs/advance/errors.html)

### 使用unwrap和expect错误处理

~~~ rust
use std::fs::File;
fn main() {
    let f = File::open("hello.txt").unwrap();
}
~~~

~~~ rust
use std::fs::File;
fn main() {
    let f = File::open("hello.txt").expect("错误的打开文件");
}
~~~

### 传播错误

~~~ rust
use ::std::fs::File;
use std::io::{self,Read};
fn read_username_from_file() -> Result<String,io::Error> {
    let f = File::open("hello.txt")；
    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };
    let mut s = String::new();
    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
~~~

#### ？

~~~ rust
use std::fs::File;
use std::io;
use std::io::Read;
fn read_username_from_file() -> Result<String,io::Error> {
    let mut f = File::open("hello.txt");
    let mut s = String::new();
    f.read_to_string(&mut s)?;  // <-- 使用“？”进行错误传递
    Ok(s)
}
~~~

<kbd>?</kbd>实际上是一个宏

~~~ rust
let mut f = match f {
    Ok(file) => file,
    Err(e) => return Err(e),
};
~~~

<kbd>?</kbd>还能进行链式调用

~~~ rust
use std::fs::File;
use std::io;
use std::io::Read;
fn read_username_form_file() -> Result<String,io::Error> {
    let mut s = String::new();
    File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
}
~~~

>   [!tip]
>
>   Rust标准库中提供了fs::read_to_string函数，该函数内部会打开一个文件、创建String，读取文件内容最后写入字符串并返回
>
>   ~~~ rust
>   use std::fs;
>   use std::io;
>   fn read_username_from_file() -> Result<String,io::Error> {
>       fs::read_to_string("hello.txt")
>   }
>   ~~~

#### ？用于Option的返回

<kbd>?</kbd>不仅可以用于Result的传播，还能用于Option的传播。Result通过?返回错误，Option通过?返回None

~~~ rust
fn last_char_of_first_line(text:&str) -> Option<char> {
    text.lines().next()?.chars().last()
}
~~~

>   [!caution]
>
>   ~~~ rust
>   fn first(arr:&[i32]) -> Option<&i32> {
>       arr.get(0)?
>   }
>   ~~~
>
>   这样写无法通过编译，因为 ? 操作符需要一个变量来承载正确的值，这个函数会返回Some(&i32)或者None，只有错误值能直接返回，正确的值不行，所以如果数组中存在0号元素，那么函数返回的是&i32而不是Some(&i32)。因此，？只能用于一下形式：
>
>   *   let v = xxx()?;
>   *   xxx()?.yyy()?;
